const fs = require('fs');
const path = require('path');

const source = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8').replace(/\r\n?/g, '\n');

const translations = {
  en: {
    lang: 'en', ogLocale: 'en_US', canonical: 'https://garciaconstrutora.com.br/en/', privacy: 'privacy-policy.html', whatsapp: 'Hello, Lucas! I would like to discuss a project.',
    strings: [
      ['Falar com a Garcia Engenharia pelo WhatsApp', 'Chat with Garcia Engineering on WhatsApp'], ['Engenheiro-chefe', 'Lead engineer'],
      ['Engenharia, arquitetura, execução de obras, acessibilidade e regularização em São José do Rio Preto. Fale com a Garcia Engenharia & Construção.', 'Engineering, architecture, construction, accessibility and property regularization in São José do Rio Preto. Contact Garcia Engineering & Construction.'],
      ['Engenharia e Construção em São José do Rio Preto | Garcia', 'Engineering and Construction in São José do Rio Preto | Garcia'],
      ['Projetos, execução de obras, acessibilidade e regularização com acompanhamento técnico em São José do Rio Preto.', 'Design, construction, accessibility and property regularization with technical oversight in São José do Rio Preto.'],
      ['Projetos, execução de obras, acessibilidade e regularização com acompanhamento técnico.', 'Design, construction, accessibility and property regularization with technical oversight.'],
      ['Ir para o conteúdo principal', 'Skip to main content'], ['Garcia Engenharia - início', 'Garcia Engineering - home'],
      ['Abrir menu', 'Open menu'], ['Navegação principal', 'Main navigation'], ['Quem somos', 'About us'], ['Serviços', 'Services'], ['Como trabalhamos', 'How we work'], ['Fale no WhatsApp', 'Chat on WhatsApp'],
      ['Selecionar idioma', 'Select language'], ['Engenharia • Arquitetura • Construção', 'Engineering • Architecture • Construction'],
      ['Projeto e execução com <span>clareza em cada etapa.</span>', 'Design and construction with <span>clarity at every stage.</span>'],
      ['Arquitetura, engenharia e construção acompanhadas do planejamento ao acabamento.', 'Architecture, engineering and construction managed from planning through completion.'],
      ['Solicitar orçamento pelo WhatsApp', 'Request a quote on WhatsApp'], ['Conhecer nossos serviços', 'Explore our services'], ['Desde 2020', 'Since 2020'],
      ['Atendimento em São José do Rio Preto e região.', 'Serving São José do Rio Preto and the surrounding region.'], ['Conhecer a Garcia Engenharia', 'Learn about Garcia Engineering'],
      ['Lucas Garcia, fundador e engenheiro-chefe da Garcia Engenharia & Construção', 'Lucas Garcia, founder and lead engineer at Garcia Engineering & Construction'], ['Fundador e engenheiro-chefe', 'Founder and lead engineer'],
      ['Engenharia e arquitetura para todos, com qualidade em cada etapa.', 'Engineering and architecture for everyone, with quality at every stage.'],
      ['Fundada em 2020 pelo engenheiro Lucas Garcia, a Garcia Engenharia & Construção nasceu com o propósito de tornar a engenharia e a arquitetura mais acessíveis, sem abrir mão da qualidade técnica, da inovação e do cuidado em cada decisão.', 'Founded in 2020 by engineer Lucas Garcia, Garcia Engineering & Construction was created to make engineering and architecture more accessible without compromising technical quality, innovation or attention to every decision.'],
      ['Do projeto à execução, transformamos necessidades complexas em soluções claras e viáveis, acompanhando cada etapa para que o cliente construa com mais segurança e tranquilidade.', 'From design to construction, we turn complex requirements into clear, feasible solutions and oversee every stage so clients can build with greater confidence and peace of mind.'],
      ['Precisão técnica, planejamento e proximidade.', 'Technical precision, planning and close support.'], ['Serviços de engenharia e construção', 'Engineering and construction services'], ['Engenharia e execução de obras', 'Engineering and construction delivery'], ['Projetos de acessibilidade', 'Accessibility design'], ['Regularização de imóveis', 'Property regularization'], ['O que fazemos', 'What we do'],
      ['Serviços para planejar, viabilizar e executar sua obra.', 'Services to plan, enable and deliver your project.'],
      ['Uma estrutura pensada para atender desde quem está começando um projeto até quem precisa executar, regularizar ou acompanhar uma obra.', 'A complete structure for clients starting a project or needing construction, property regularization or technical oversight.'],
      ['Projetos arquitetônicos', 'Architectural design'], ['Concepção de espaços funcionais, contemporâneos e alinhados às necessidades do cliente.', 'Functional, contemporary spaces designed around each client’s needs.'],
      ['Engenharia e execução', 'Engineering and construction'], ['Planejamento e execução da obra do básico ao acabamento, com acompanhamento técnico.', 'Planning and construction from structural work through finishes, with technical oversight.'],
      ['Terreno e construção', 'Site and construction'], ['Apoio na análise do terreno, definição do projeto e desenvolvimento da construção.', 'Support with site analysis, project definition and construction development.'],
      ['Regularização', 'Property regularization'], ['Suporte técnico e documental para aprovações e processos junto à prefeitura.', 'Technical and documentation support for municipal approvals and procedures.'],
      ['Diferenciais na prática', 'Our approach in practice'], ['Serviços concretos, com responsabilidade técnica.', 'Practical services backed by technical responsibility.'],
      ['Pontos presentes nos trabalhos realizados pela Garcia e reconhecidos nas avaliações dos clientes.', 'Qualities reflected in Garcia’s work and recognized in client reviews.'],
      ['Projeto, execução e acompanhamento', 'Design, construction and oversight'], ['O escopo pode reunir projeto arquitetônico, planejamento, execução da obra e acompanhamento técnico até o acabamento.', 'The scope may combine architectural design, planning, construction and technical oversight through completion.'],
      ['Aprovação e regularização', 'Approval and regularization'], ['Suporte com projetos, alvarás, Habite-se e processos de regularização junto à prefeitura.', 'Support with designs, permits, occupancy certificates and municipal regularization procedures.'],
      ['Acessibilidade conforme a NBR 9050', 'Accessibility in accordance with NBR 9050'], ['Projetos e adaptações de acessibilidade para residências e estabelecimentos comerciais.', 'Accessibility designs and adaptations for homes and commercial properties.'],
      ['Escopo definido e atendimento próximo', 'Clear scope and close support'], ['Necessidades, entregas e responsabilidades são alinhadas antes do início de cada serviço.', 'Requirements, deliverables and responsibilities are aligned before each service begins.'],
      ['Avaliações no Google', 'Google Reviews'], ['A confiança de quem já construiu com a Garcia.', 'Trusted by clients who have built with Garcia.'], ['Cinco estrelas', 'Five stars'], ['Experiências publicadas por clientes no Google', 'Experiences shared by clients on Google'], ['Avaliação no Google', 'Google review'], ['Ver todas as avaliações no Google', 'View all Google reviews'],
      ['“Fiquei muito satisfeito com o projeto de acessibilidade feito pela Garcia Engenharia. Domínio total das normas técnicas (NBR 9050) e entrega no prazo. Profissionais de confiança!”', '“I was very satisfied with the accessibility project delivered by Garcia Engineering. Complete command of the technical standards (NBR 9050) and on-time delivery. Professionals you can trust!”'],
      ['“Serviço de execução de obra por empreitada com preço fechado e muita transparência. O acompanhamento técnico do engenheiro fez toda a diferença no acabamento final.”', '“Fixed-price construction service delivered with great transparency. The engineer’s technical oversight made all the difference to the final finish.”'],
      ['“Fizeram todo o meu projeto arquitetônico e projeto estrutural. Conseguiram o Alvará de Construção em tempo recorde. Engenharia de alto nível e suporte constante durante a obra.”', '“They completed my entire architectural and structural design. They obtained the construction permit in record time. High-level engineering and continuous support throughout construction.”'],
      ['Como trabalhamos', 'How we work'], ['Um processo claro do primeiro contato à entrega.', 'A clear process from first contact to delivery.'], ['Entendimento', 'Discovery'], ['Levantamos necessidades, referências, terreno, prazo e objetivos do projeto.', 'We identify requirements, references, site conditions, timelines and project goals.'], ['Projeto', 'Design'], ['Desenvolvemos a solução arquitetônica e técnica, refinando cada detalhe.', 'We develop the architectural and technical solution, refining every detail.'], ['Planejamento', 'Planning'], ['Organizamos etapas, materiais, fornecedores e execução de forma coordenada.', 'We coordinate stages, materials, suppliers and construction.'], ['Obra', 'Construction'], ['Acompanhamos a execução até a finalização, mantendo o padrão definido em projeto.', 'We oversee construction through completion, maintaining the standards established in the design.'],
      ['Perguntas frequentes', 'Frequently asked questions'], ['Antes de começar seu projeto.', 'Before starting your project.'], ['As condições específicas de prazo, escopo e investimento são definidas após entendermos o imóvel e o serviço necessário.', 'Specific timelines, scope and investment are defined after we understand the property and the required service.'], ['Tirar uma dúvida pelo WhatsApp', 'Ask a question on WhatsApp'],
      ['Quais serviços a Garcia realiza?', 'What services does Garcia provide?'], ['Projetos arquitetônicos e de engenharia, acessibilidade, regularização, documentação, execução e acompanhamento técnico de obras.', 'Architectural and engineering design, accessibility, regularization, documentation, construction and technical oversight.'], ['Posso contratar somente o projeto?', 'Can I hire Garcia for design only?'], ['Sim. O escopo pode contemplar somente projeto e documentação, acompanhamento técnico ou a execução completa, conforme a necessidade.', 'Yes. The scope may cover design and documentation only, technical oversight or complete construction, depending on your needs.'], ['Como funciona o orçamento?', 'How does the quote process work?'], ['No primeiro contato são levantados o tipo de imóvel, a localização, o serviço necessário e o estágio atual. Com essas informações, a Garcia define o escopo e apresenta a proposta.', 'During the first contact, we identify the property type, location, required service and current stage. Garcia then defines the scope and presents a proposal.'], ['A Garcia cuida de alvará e regularização?', 'Does Garcia handle permits and regularization?'], ['Sim. A empresa atua com projetos, alvarás, Habite-se e processos de regularização junto à prefeitura, de acordo com cada caso.', 'Yes. The company handles designs, permits, occupancy certificates and municipal regularization procedures according to each case.'], ['Qual é a região de atendimento?', 'What area do you serve?'], ['A Garcia está em São José do Rio Preto. A disponibilidade para cidades da região é confirmada durante o atendimento inicial.', 'Garcia is based in São José do Rio Preto. Availability in nearby cities is confirmed during the initial consultation.'],
      ['Seu próximo projeto começa aqui', 'Your next project starts here'], ['Vamos construir uma ideia juntos?', 'Let’s build an idea together.'], ['Conte o que você pretende construir, reformar ou regularizar. A Garcia avalia a necessidade e orienta o próximo passo.', 'Tell us what you plan to build, renovate or regularize. Garcia will assess your needs and recommend the next step.'], ['Falar no WhatsApp', 'Chat on WhatsApp'], ['Ver Instagram', 'View Instagram'], ['Diferenciais', 'Approach'], ['Processo', 'Process'], ['Política de privacidade', 'Privacy policy'], ['Desenvolvido por Funil Digital', 'Developed by Funil Digital'],
      ['Preferências de privacidade', 'Privacy preferences'], ['Usamos métricas de acesso para entender o desempenho do site. Você pode aceitar ou continuar sem cookies de análise.', 'We use access metrics to understand site performance. You can accept or continue without analytics cookies.'], ['Saiba mais', 'Learn more'], ['Continuar sem aceitar', 'Continue without accepting'], ['Aceitar métricas', 'Accept analytics']
    ]
  },
  es: {
    lang: 'es', ogLocale: 'es_ES', canonical: 'https://garciaconstrutora.com.br/es/', privacy: 'politica-de-privacidad.html', whatsapp: '¡Hola, Lucas! Me gustaría conversar sobre un proyecto.',
    strings: [
      ['Falar com a Garcia Engenharia pelo WhatsApp', 'Hablar con Garcia Ingeniería por WhatsApp'], ['Engenheiro-chefe', 'Ingeniero jefe'],
      ['Serviços de engenharia e construção', 'Servicios de ingeniería y construcción'], ['Engenharia e execução de obras', 'Ingeniería y ejecución de obras'], ['Projetos de acessibilidade', 'Proyectos de accesibilidad'], ['Regularização de imóveis', 'Regularización de inmuebles'],
      ['Engenharia, arquitetura, execução de obras, acessibilidade e regularização em São José do Rio Preto. Fale com a Garcia Engenharia & Construção.', 'Ingeniería, arquitectura, ejecución de obras, accesibilidad y regularización en São José do Rio Preto. Contacte con Garcia Ingeniería y Construcción.'],
      ['Engenharia e Construção em São José do Rio Preto | Garcia', 'Ingeniería y Construcción en São José do Rio Preto | Garcia'], ['Projetos, execução de obras, acessibilidade e regularização com acompanhamento técnico em São José do Rio Preto.', 'Proyectos, ejecución de obras, accesibilidad y regularización con supervisión técnica en São José do Rio Preto.'], ['Projetos, execução de obras, acessibilidade e regularização com acompanhamento técnico.', 'Proyectos, ejecución de obras, accesibilidad y regularización con supervisión técnica.'],
      ['Ir para o conteúdo principal', 'Ir al contenido principal'], ['Garcia Engenharia - início', 'Garcia Ingeniería - inicio'], ['Abrir menu', 'Abrir menú'], ['Navegação principal', 'Navegación principal'], ['Quem somos', 'Quiénes somos'], ['Serviços', 'Servicios'], ['Como trabalhamos', 'Cómo trabajamos'], ['Fale no WhatsApp', 'Hable por WhatsApp'], ['Selecionar idioma', 'Seleccionar idioma'],
      ['Engenharia • Arquitetura • Construção', 'Ingeniería • Arquitectura • Construcción'], ['Projeto e execução com <span>clareza em cada etapa.</span>', 'Proyecto y ejecución con <span>claridad en cada etapa.</span>'], ['Arquitetura, engenharia e construção acompanhadas do planejamento ao acabamento.', 'Arquitectura, ingeniería y construcción acompañadas desde la planificación hasta los acabados.'], ['Solicitar orçamento pelo WhatsApp', 'Solicitar presupuesto por WhatsApp'], ['Conhecer nossos serviços', 'Conocer nuestros servicios'], ['Desde 2020', 'Desde 2020'], ['Atendimento em São José do Rio Preto e região.', 'Atención en São José do Rio Preto y región.'], ['Conhecer a Garcia Engenharia', 'Conocer Garcia Ingeniería'],
      ['Lucas Garcia, fundador e engenheiro-chefe da Garcia Engenharia & Construção', 'Lucas Garcia, fundador e ingeniero jefe de Garcia Ingeniería y Construcción'], ['Fundador e engenheiro-chefe', 'Fundador e ingeniero jefe'], ['Engenharia e arquitetura para todos, com qualidade em cada etapa.', 'Ingeniería y arquitectura para todos, con calidad en cada etapa.'], ['Fundada em 2020 pelo engenheiro Lucas Garcia, a Garcia Engenharia & Construção nasceu com o propósito de tornar a engenharia e a arquitetura mais acessíveis, sem abrir mão da qualidade técnica, da inovação e do cuidado em cada decisão.', 'Fundada en 2020 por el ingeniero Lucas Garcia, Garcia Ingeniería y Construcción nació para hacer la ingeniería y la arquitectura más accesibles, sin renunciar a la calidad técnica, la innovación y el cuidado en cada decisión.'], ['Do projeto à execução, transformamos necessidades complexas em soluções claras e viáveis, acompanhando cada etapa para que o cliente construa com mais segurança e tranquilidade.', 'Del proyecto a la ejecución, transformamos necesidades complejas en soluciones claras y viables, acompañando cada etapa para que el cliente construya con mayor seguridad y tranquilidad.'], ['Precisão técnica, planejamento e proximidade.', 'Precisión técnica, planificación y cercanía.'],
      ['O que fazemos', 'Qué hacemos'], ['Serviços para planejar, viabilizar e executar sua obra.', 'Servicios para planificar, viabilizar y ejecutar su obra.'], ['Uma estrutura pensada para atender desde quem está começando um projeto até quem precisa executar, regularizar ou acompanhar uma obra.', 'Una estructura pensada tanto para quien inicia un proyecto como para quien necesita ejecutar, regularizar o supervisar una obra.'], ['Projetos arquitetônicos', 'Proyectos arquitectónicos'], ['Concepção de espaços funcionais, contemporâneos e alinhados às necessidades do cliente.', 'Diseño de espacios funcionales, contemporáneos y alineados con las necesidades del cliente.'], ['Engenharia e execução', 'Ingeniería y ejecución'], ['Planejamento e execução da obra do básico ao acabamento, com acompanhamento técnico.', 'Planificación y ejecución de la obra desde la estructura hasta los acabados, con supervisión técnica.'], ['Terreno e construção', 'Terreno y construcción'], ['Apoio na análise do terreno, definição do projeto e desenvolvimento da construção.', 'Apoyo en el análisis del terreno, definición del proyecto y desarrollo de la construcción.'], ['Regularização', 'Regularización'], ['Suporte técnico e documental para aprovações e processos junto à prefeitura.', 'Soporte técnico y documental para aprobaciones y trámites municipales.'],
      ['Diferenciais na prática', 'Diferenciales en la práctica'], ['Serviços concretos, com responsabilidade técnica.', 'Servicios concretos con responsabilidad técnica.'], ['Pontos presentes nos trabalhos realizados pela Garcia e reconhecidos nas avaliações dos clientes.', 'Cualidades presentes en los trabajos de Garcia y reconocidas en las opiniones de los clientes.'], ['Projeto, execução e acompanhamento', 'Proyecto, ejecución y supervisión'], ['O escopo pode reunir projeto arquitetônico, planejamento, execução da obra e acompanhamento técnico até o acabamento.', 'El alcance puede reunir proyecto arquitectónico, planificación, ejecución y supervisión técnica hasta los acabados.'], ['Aprovação e regularização', 'Aprobación y regularización'], ['Suporte com projetos, alvarás, Habite-se e processos de regularização junto à prefeitura.', 'Apoyo con proyectos, permisos, certificados de ocupación y trámites de regularización municipal.'], ['Acessibilidade conforme a NBR 9050', 'Accesibilidad según la NBR 9050'], ['Projetos e adaptações de acessibilidade para residências e estabelecimentos comerciais.', 'Proyectos y adaptaciones de accesibilidad para viviendas y establecimientos comerciales.'], ['Escopo definido e atendimento próximo', 'Alcance definido y atención cercana'], ['Necessidades, entregas e responsabilidades são alinhadas antes do início de cada serviço.', 'Las necesidades, entregas y responsabilidades se acuerdan antes de iniciar cada servicio.'],
      ['Avaliações no Google', 'Opiniones en Google'], ['A confiança de quem já construiu com a Garcia.', 'La confianza de quienes ya construyeron con Garcia.'], ['Cinco estrelas', 'Cinco estrellas'], ['Experiências publicadas por clientes no Google', 'Experiencias publicadas por clientes en Google'], ['Avaliação no Google', 'Opinión en Google'], ['Ver todas as avaliações no Google', 'Ver todas las opiniones en Google'],
      ['“Fiquei muito satisfeito com o projeto de acessibilidade feito pela Garcia Engenharia. Domínio total das normas técnicas (NBR 9050) e entrega no prazo. Profissionais de confiança!”', '“Quedé muy satisfecho con el proyecto de accesibilidad realizado por Garcia Ingeniería. Dominio total de las normas técnicas (NBR 9050) y entrega puntual. ¡Profesionales de confianza!”'],
      ['“Serviço de execução de obra por empreitada com preço fechado e muita transparência. O acompanhamento técnico do engenheiro fez toda a diferença no acabamento final.”', '“Servicio de ejecución de obra a precio cerrado y con mucha transparencia. La supervisión técnica del ingeniero marcó la diferencia en el acabado final.”'],
      ['“Fizeram todo o meu projeto arquitetônico e projeto estrutural. Conseguiram o Alvará de Construção em tempo recorde. Engenharia de alto nível e suporte constante durante a obra.”', '“Realizaron todo mi proyecto arquitectónico y estructural. Obtuvieron el permiso de construcción en tiempo récord. Ingeniería de alto nivel y apoyo constante durante la obra.”'],
      ['Como trabalhamos', 'Cómo trabajamos'], ['Um processo claro do primeiro contato à entrega.', 'Un proceso claro desde el primer contacto hasta la entrega.'], ['Entendimento', 'Comprensión'], ['Levantamos necessidades, referências, terreno, prazo e objetivos do projeto.', 'Identificamos necesidades, referencias, terreno, plazo y objetivos del proyecto.'], ['Projeto', 'Proyecto'], ['Desenvolvemos a solução arquitetônica e técnica, refinando cada detalhe.', 'Desarrollamos la solución arquitectónica y técnica, perfeccionando cada detalle.'], ['Planejamento', 'Planificación'], ['Organizamos etapas, materiais, fornecedores e execução de forma coordenada.', 'Organizamos etapas, materiales, proveedores y ejecución de forma coordinada.'], ['Obra', 'Obra'], ['Acompanhamos a execução até a finalização, mantendo o padrão definido em projeto.', 'Supervisamos la ejecución hasta su finalización, manteniendo el estándar definido en el proyecto.'],
      ['Perguntas frequentes', 'Preguntas frecuentes'], ['Antes de começar seu projeto.', 'Antes de comenzar su proyecto.'], ['As condições específicas de prazo, escopo e investimento são definidas após entendermos o imóvel e o serviço necessário.', 'Las condiciones específicas de plazo, alcance e inversión se definen después de comprender el inmueble y el servicio necesario.'], ['Tirar uma dúvida pelo WhatsApp', 'Consultar por WhatsApp'], ['Quais serviços a Garcia realiza?', '¿Qué servicios ofrece Garcia?'], ['Projetos arquitetônicos e de engenharia, acessibilidade, regularização, documentação, execução e acompanhamento técnico de obras.', 'Proyectos arquitectónicos y de ingeniería, accesibilidad, regularización, documentación, ejecución y supervisión técnica de obras.'], ['Posso contratar somente o projeto?', '¿Puedo contratar solamente el proyecto?'], ['Sim. O escopo pode contemplar somente projeto e documentação, acompanhamento técnico ou a execução completa, conforme a necessidade.', 'Sí. El alcance puede incluir solamente proyecto y documentación, supervisión técnica o ejecución completa, según la necesidad.'], ['Como funciona o orçamento?', '¿Cómo funciona el presupuesto?'], ['No primeiro contato são levantados o tipo de imóvel, a localização, o serviço necessário e o estágio atual. Com essas informações, a Garcia define o escopo e apresenta a proposta.', 'En el primer contacto se identifican el tipo de inmueble, la ubicación, el servicio necesario y la etapa actual. Con esta información, Garcia define el alcance y presenta la propuesta.'], ['A Garcia cuida de alvará e regularização?', '¿Garcia gestiona permisos y regularización?'], ['Sim. A empresa atua com projetos, alvarás, Habite-se e processos de regularização junto à prefeitura, de acordo com cada caso.', 'Sí. La empresa trabaja con proyectos, permisos, certificados de ocupación y procesos de regularización municipal según cada caso.'], ['Qual é a região de atendimento?', '¿Cuál es la zona de atención?'], ['A Garcia está em São José do Rio Preto. A disponibilidade para cidades da região é confirmada durante o atendimento inicial.', 'Garcia se encuentra en São José do Rio Preto. La disponibilidad para ciudades de la región se confirma durante la atención inicial.'],
      ['Seu próximo projeto começa aqui', 'Su próximo proyecto comienza aquí'], ['Vamos construir uma ideia juntos?', '¿Construimos una idea juntos?'], ['Conte o que você pretende construir, reformar ou regularizar. A Garcia avalia a necessidade e orienta o próximo passo.', 'Cuéntenos qué desea construir, reformar o regularizar. Garcia evalúa la necesidad y le orienta sobre el siguiente paso.'], ['Falar no WhatsApp', 'Hablar por WhatsApp'], ['Ver Instagram', 'Ver Instagram'], ['Diferenciais', 'Diferenciales'], ['Processo', 'Proceso'], ['Política de privacidade', 'Política de privacidad'], ['Desenvolvido por Funil Digital', 'Desarrollado por Funil Digital'],
      ['Preferências de privacidade', 'Preferencias de privacidad'], ['Usamos métricas de acesso para entender o desempenho do site. Você pode aceitar ou continuar sem cookies de análise.', 'Usamos métricas de acceso para comprender el rendimiento del sitio. Puede aceptar o continuar sin cookies de análisis.'], ['Saiba mais', 'Más información'], ['Continuar sem aceitar', 'Continuar sin aceptar'], ['Aceitar métricas', 'Aceptar métricas']
    ]
  }
};

for (const [locale, config] of Object.entries(translations)) {
  let html = source;
  for (const [from, to] of [...config.strings].sort((a, b) => b[0].length - a[0].length)) {
    html = html.split(from).join(to);
  }
  html = html.replace(/\n\s*<section class="section projects"[\s\S]*?<\/section>/, '');
  html = html.replace('<html lang="pt-BR">', `<html lang="${config.lang}">`)
    .replace('<meta property="og:locale" content="pt_BR" />', `<meta property="og:locale" content="${config.ogLocale}" />`)
    .replaceAll('https://garciaconstrutora.com.br/"', `${config.canonical}"`)
    .replace(`<link rel="alternate" hreflang="pt-BR" href="${config.canonical}"`, '<link rel="alternate" hreflang="pt-BR" href="https://garciaconstrutora.com.br/"')
    .replace(`<link rel="alternate" hreflang="x-default" href="${config.canonical}"`, '<link rel="alternate" hreflang="x-default" href="https://garciaconstrutora.com.br/"')
    .replaceAll('href="./" lang="pt-BR" aria-current="page"', 'href="../" lang="pt-BR"')
    .replaceAll(`href="${locale}/" lang="${config.lang}"`, `href="./" lang="${config.lang}" aria-current="page"`)
    .replaceAll('href="es/"', 'href="../es/"')
    .replaceAll('href="en/"', 'href="../en/"')
    .replaceAll('href="assets/', 'href="../assets/')
    .replaceAll('src="assets/', 'src="../assets/')
    .replaceAll('url("assets/', 'url("../assets/')
    .replaceAll('href="styles.css', 'href="../styles.css')
    .replaceAll('src="script.js"', 'src="../script.js"')
    .replaceAll('href="politica-de-privacidade.html"', `href="${config.privacy}"`);
  html = html.replaceAll('text=Ol%C3%A1%2C%20Lucas%21%20Gostaria%20de%20conversar%20sobre%20um%20projeto.', `text=${encodeURIComponent(config.whatsapp)}`)
    .replaceAll('https://garciaconstrutora.com.br/#empresa', `${config.canonical}#empresa`);

  const directory = path.join(__dirname, locale);
  fs.mkdirSync(directory, { recursive: true });
  fs.writeFileSync(path.join(directory, 'index.html'), html);
}
